---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: todoapp
type: Opaque
data:
  SECRET_KEY: "QGUyKHl4KXYmdGdoM19zPTB5amEtaSFkcGVieHN6XmRnNDd4KS1rJmtxXzN6Zio5ZSoK"
  NAME: "dG9kb2Ri"
  USER: "dXNlcg=="
  PASSWORD: "dXNlci1wYXNzd29yZA=="
  HOST: "bXlzcWwubXlzcWwtaGVhZGxlc3Mtc2VydmljZS5teXNxbC5zdmMuY2x1c3Rlci5sb2NhbA=="
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: mysql
type: Opaque
data:
  DATABASE_CONNECTION: "bXlzcWwrbXlzcWxjb25uZWN0b3I6Ly91c2VyOnVzZXItcGFzc3dvcmRAbXlzcWwtMC5teXNxbC1oZWFkbGVzcy1zZXJ2aWNlLm15c3FsLnN2Yy5jbHVzdGVyLmxvY2FsL3RvZG9kYg=="
  MYSQL_DATABASE: "dG9kb2Ri"
  MYSQL_ROOT_PASSWORD: "bXktc2VjcmV0LXB3"
  MYSQL_USER: "dXNlcg==" 
  MYSQL_PASSWORD: "dXNlci1wYXNzd29yZA=="