apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: todoapp
type: Opaque
data:
  SECRET_KEY: "QGUyKHl4KXYmdGdoM19zPTB5amEtaSFkcGVieHN6XmRnNDd4KS1rJmtxXzN6Zio5ZSoK"
  DATABASE_CONNECTION: "bXlzcWwrbXlzcWxjb25uZWN0b3I6Ly9yb290Om15LXNlY3JldC1wd0BteXNxbC0wLm15c3FsLWhlYWRsZXNzLXNlcnZpY2UubXlzcWwuc3ZjLmNsdXN0ZXIubG9jYWwvdG9kb2Ri="
  NAME: "dG9kb2Ri"
  PASSWORD: "bXktc2VjcmV0LXB3"
  USER: "cm9vdA=="