apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: todoapp
type: Opaque
data:
  SECRET_KEY: "QGUyKHl4KXYmdGdoM19zPTB5amEtaSFkcGVieHN6XmRnNDd4KS1rJmtxXzN6Zio5ZSoK"
  NAME: "dG9kb2Ri"
  USER: "dXNlcg=="
  PASSWORD: "dXNlci1wYXNzd29yZA=="
  HOST: "bXlzcWwtMC5teXNxbC1oZWFkbGVzcy1zZXJ2aWNlLm15c3FsLnN2Yy5jbHVzdGVyLmxvY2Fs"
